import CHAMPIONS from "./champions";
export const ROLES = ["TOP", "MID", "BOT", "JUNGLE", "SUPPORT"] as const;

export type Role = (typeof ROLES)[number];

type ChampionList = Record<keyof typeof CHAMPIONS, Role[]>;

export const CHAMPION_ROLES: ChampionList = {
    Aatrox: ["TOP"],
    Ahri: ["MID"],
    Akali: ["MID", "TOP"],
    Akshan: ["MID", "TOP"],
    Alistar: ["SUPPORT"],
    Ambessa: ["TOP", "JUNGLE"],
    Amumu: ["JUNGLE"],
    Anivia: ["MID"],
    Annie: ["MID", "SUPPORT"],
    Aphelios: ["BOT"],
    Ashe: ["BOT", "SUPPORT"],
    AurelionSol: ["MID"],
    Aurora: ["MID", "TOP"],
    Azir: ["MID"],
    Bard: ["SUPPORT"],
    Belveth: ["JUNGLE"],
    Blitzcrank: ["SUPPORT"],
    Brand: ["MID", "JUNGLE", "BOT", "SUPPORT"],
    Braum: ["SUPPORT"],
    Briar: ["JUNGLE"],
    Caitlyn: ["BOT", "MID"],
    Camille: ["TOP", "SUPPORT"],
    Cassiopeia: ["TOP", "MID"],
    Chogath: ["TOP"],
    Corki: ["TOP"],
    Darius: ["TOP"],
    Diana: ["JUNGLE", "MID"],
    Draven: ["BOT"],
    DrMundo: ["TOP"],
    Ekko: ["JUNGLE", "MID"],
    Elise: ["MID", "SUPPORT"],
    Evelynn: ["JUNGLE"],
    Ezreal: ["BOT", "MID"],
    Fiddlesticks: ["JUNGLE"],
    Fiora: ["TOP"],
    Fizz: ["MID"],
    Galio: ["MID"],
    Gangplank: ["TOP"],
    Garen: ["TOP"],
    Gnar: ["TOP"],
    Gragas: ["TOP", "JUNGLE"],
    Graves: ["JUNGLE"],
    Gwen: ["TOP", "JUNGLE"],
    Hecarim: ["JUNGLE"],
    Heimerdinger: ["TOP", "BOT", "SUPPORT"],
    Hwei: ["MID", "BOT", "SUPPORT"],
    Illaoi: ["TOP"],
    Irelia: ["TOP", "MID"],
    Ivern: ["JUNGLE"],
    Janna: ["SUPPORT"],
    JarvanIV: ["JUNGLE"],
    Jax: ["TOP", "JUNGLE"],
    Jayce: ["TOP"],
    Jhin: ["BOT", "MID"],
    Jinx: ["BOT"],
    Kaisa: ["BOT", "MID"],
    Kalista: ["BOT"],
    Karma: ["SUPPORT", "MID"],
    Karthus: ["JUNGLE", "BOT"],
    Kassadin: ["MID"],
    Katarina: ["MID"],
    Kayle: ["TOP"],
    Kayn: ["JUNGLE", "TOP"],
    Kennen: ["TOP"],
    Khazix: ["JUNGLE"],
    Kindred: ["JUNGLE"],
    Kled: ["TOP"],
    KogMaw: ["BOT"],
    KSante: ["TOP"],
    Leblanc: ["MID"],
    LeeSin: ["JUNGLE", "TOP"],
    Leona: ["SUPPORT"],
    Lillia: ["JUNGLE"],
    Lissandra: ["TOP", "MID"],
    Lucian: ["BOT", "MID"],
    Lulu: ["SUPPORT"],
    Lux: ["BOT", "SUPPORT", "MID"],
    Malphite: ["TOP", "JUNGLE", "MID", "SUPPORT"],
    Malzahar: ["MID"],
    Maokai: ["TOP", "JUNGLE", "SUPPORT"],
    MasterYi: ["JUNGLE"],
    Mel: ["MID", "SUPPORT"],
    Milio: ["SUPPORT"],
    MissFortune: ["BOT"],
    MonkeyKing: ["JUNGLE", "TOP"],
    Mordekaiser: ["TOP", "JUNGLE"],
    Morgana: ["SUPPORT", "JUNGLE"],
    Naafiri: ["TOP", "MID"],
    Nami: ["SUPPORT"],
    Nasus: ["TOP", "MID"],
    Nautilus: ["SUPPORT"],
    Neeko: ["MID", "SUPPORT", "JUNGLE"],
    Nidalee: ["JUNGLE"],
    Nilah: ["BOT"],
    Nocturne: ["JUNGLE"],
    Nunu: ["JUNGLE"],
    Olaf: ["TOP", "JUNGLE"],
    Orianna: ["MID"],
    Ornn: ["TOP"],
    Pantheon: ["TOP", "MID", "JUNGLE", "SUPPORT"],
    Poppy: ["TOP", "JUNGLE", "SUPPORT"],
    Pyke: ["SUPPORT"],
    Qiyana: ["MID"],
    Quinn: ["TOP"],
    Rakan: ["SUPPORT"],
    Rammus: ["TOP", "JUNGLE"],
    RekSai: ["JUNGLE"],
    Rell: ["SUPPORT"],
    Renata: ["SUPPORT"],
    Renekton: ["TOP"],
    Rengar: ["JUNGLE", "TOP"],
    Riven: ["TOP"],
    Rumble: ["TOP", "SUPPORT"],
    Ryze: ["MID"],
    Samira: ["BOT"],
    Sejuani: ["JUNGLE"],
    Senna: ["BOT", "SUPPORT"],
    Seraphine: ["BOT", "SUPPORT"],
    Sett: ["TOP", "MID"],
    Shaco: ["JUNGLE", "SUPPORT", "TOP"],
    Shen: ["TOP", "SUPPORT"],
    Shyvana: ["JUNGLE"],
    Singed: ["TOP", "SUPPORT"],
    Sion: ["TOP", "MID"],
    Sivir: ["BOT"],
    Skarner: ["JUNGLE", "TOP"],
    Smolder: ["TOP", "MID", "BOT"],
    Sona: ["SUPPORT"],
    Soraka: ["SUPPORT"],
    Swain: ["MID", "BOT", "SUPPORT"],
    Sylas: ["MID", "JUNGLE"],
    Syndra: ["MID"],
    TahmKench: ["TOP", "SUPPORT"],
    Taliyah: ["JUNGLE", "MID", "SUPPORT"],
    Talon: ["MID", "JUNGLE"],
    Taric: ["SUPPORT"],
    Teemo: ["TOP", "SUPPORT"],
    Thresh: ["SUPPORT"],
    Tristana: ["MID", "BOT"],
    Trundle: ["TOP", "JUNGLE"],
    Tryndamere: ["TOP"],
    TwistedFate: ["TOP", "MID", "BOT"],
    Twitch: ["BOT", "SUPPORT"],
    Udyr: ["TOP", "JUNGLE"],
    Urgot: ["TOP"],
    Varus: ["BOT", "TOP"],
    Vayne: ["BOT", "TOP"],
    Veigar: ["MID", "BOT"],
    Velkoz: ["MID", "BOT", "SUPPORT"],
    Vex: ["MID"],
    Vi: ["JUNGLE"],
    Viego: ["JUNGLE"],
    Viktor: ["MID"],
    Vladimir: ["TOP", "MID"],
    Volibear: ["TOP", "JUNGLE"],
    Warwick: ["TOP", "JUNGLE"],
    Xayah: ["BOT"],
    Xerath: ["MID", "SUPPORT"],
    XinZhao: ["JUNGLE"],
    Yasuo: ["TOP", "MID", "BOT"],
    Yone: ["TOP", "MID"],
    Yorick: ["TOP"],
    Yuumi: ["SUPPORT"],
    Zac: ["TOP", "JUNGLE"],
    Zed: ["MID", "JUNGLE"],
    Zeri: ["BOT"],
    Ziggs: ["MID", "BOT"],
    Zilean: ["SUPPORT"],
    Zoe: ["MID", "SUPPORT"],
    Zyra: ["JUNGLE", "SUPPORT"],
};
